AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LF0:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_handler.handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::025726486846:role/service-role/LF0-role-v5z40qdv'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /chatbot
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
